package com.jmj.trade.notification;

public enum NotificationEventType {
    SYNC_SUCCEEDED,
    SYNC_FAILED,
    ANALYSIS_SUCCEEDED,
    ANALYSIS_FAILED,
    EVENT_CREATED,
    ORDER_RESULT,
    ORDER_RECONCILIATION_MANUAL_REVIEW,
    PRODUCTION_READINESS_ALERT
}
