package com.jmj.trade;

import org.flywaydb.core.Flyway;
import com.zaxxer.hikari.HikariDataSource;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.postgresql.PostgreSQLContainer;

/**
 * A JVM-wide singleton container, not one per subclass: the {@code POSTGRES} field is
 * declared on this class, so per the JLS a class is initialized at most once per
 * classloader — the static initializer runs on the first subclass touched, and every other
 * subclass in the same Surefire fork reuses that same running container.
 *
 * <p>The primary fix for CI's "FATAL: sorry, too many clients already" failure is the
 * {@code spring.datasource.hikari.maximum-pool-size} surefire system property in pom.xml,
 * which caps every {@code @SpringBootTest} context's connection pool ceiling instead of
 * leaving most of them on Hikari's unconstrained default (10 max, minIdle = max).
 * Measured peak before that fix: ~150 simultaneous connections from ~18 distinct cached
 * contexts, comfortably past Postgres's own default {@code max_connections=100}; with the
 * pool cap, baseline peak drops to roughly 18 × 2 ≈ 36. The higher {@code max_connections}
 * here is headroom on top of that baseline for whatever else is transiently open (e.g.
 * {@code PostgresContainerCapacityTest} deliberately opens ~120 raw connections at once) —
 * not something the baseline itself needs to stay under 100.
 */
public abstract class PostgresIntegrationTest {

    @ServiceConnection
    protected static final PostgreSQLContainer POSTGRES = startPostgres();

    private static String migratedFixtureSql;

    /** Cache SQL generated by real migrations; restore the complete schema and seeds per case. */
    protected static synchronized Flyway freshMigratedSchema() {
        var flyway = Flyway.configure()
                .dataSource(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword())
                .cleanDisabled(false).load();
        if (migratedFixtureSql == null) {
            flyway.clean();
            flyway.migrate();
            // INSERT output is executable through JDBC; no COPY stdin or per-case Docker exec.
            var dump = fixtureCommand("pg_dump", "--username=" + POSTGRES.getUsername(),
                    "--dbname=" + POSTGRES.getDatabaseName(), "--schema=public",
                    "--format=plain", "--inserts", "--no-owner");
            // These psql-only guards come from our trusted disposable fixture, never external dumps.
            migratedFixtureSql = dump.lines()
                    .filter(line -> !line.startsWith("\\restrict ") && !line.startsWith("\\unrestrict "))
                    .collect(java.util.stream.Collectors.joining("\n"));
        } else {
            try (var connection = POSTGRES.createConnection(""); var statement = connection.createStatement()) {
                statement.execute("DROP SCHEMA public CASCADE");
                statement.execute(migratedFixtureSql);
            } catch (java.sql.SQLException failure) {
                throw new IllegalStateException("Disposable database fixture restore failed (SQLState="
                        + failure.getSQLState() + ")");
            }
        }
        return flyway;
    }

    protected static HikariDataSource pooledTestDataSource() {
        var source = new HikariDataSource();
        source.setJdbcUrl(POSTGRES.getJdbcUrl());
        source.setUsername(POSTGRES.getUsername());
        source.setPassword(POSTGRES.getPassword());
        source.setMaximumPoolSize(2);
        return source;
    }

    private static String fixtureCommand(String... command) {
        try {
            var result = POSTGRES.execInContainer(command);
            if (result.getExitCode() != 0) {
                // Fixture diagnostics identify the category, never SQL/data or credentials.
                var stderr = result.getStderr();
                var category = stderr.contains("already exists") ? "object already exists"
                        : stderr.contains("does not exist") ? "object missing"
                        : stderr.contains("permission denied") ? "permission denied"
                        : stderr.contains("unsupported version") ? "unsupported archive version"
                        : stderr.contains("could not open") ? "archive unavailable"
                        : "unclassified command error";
                throw new IllegalStateException("Disposable database fixture " + command[0]
                        + " failed (exit=" + result.getExitCode() + ", " + category + ")");
            }
            return result.getStdout();
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Disposable database fixture interrupted", interrupted);
        } catch (java.io.IOException unavailable) {
            throw new IllegalStateException("Disposable database fixture unavailable", unavailable);
        }
    }

    private static PostgreSQLContainer startPostgres() {
        var postgres = new PostgreSQLContainer("postgres:17-alpine")
                // withCommand replaces Testcontainers' default command, including fsync=off.
                // Restore that default for this disposable fixture; production Compose is unaffected.
                .withCommand("postgres", "-c", "fsync=off", "-c", "max_connections=300");
        postgres.start();
        return postgres;
    }
}
